---
title: (Potential) BrainGlobe Roadmap
author: Adam Tyson
execute: 
  enabled: true
format:
    revealjs:
        theme: [default, niu-dark.scss]
        logo: img/logo_niu_dark.png
        footer: "2023-11-01"
        slide-number: c
        menu:
            numbers: true
        chalkboard: true
        scrollable: true
        preview-links: false
        view-distance: 10
        mobile-view-distance: 10
        auto-animate: true
        auto-play-media: true
        code-overflow: wrap
        highlight-style: atom-one
        mermaid: 
          theme: neutral
          fontFamily: arial
          curve: linear
    html:
        theme: [default, niu-dark.scss]
        logo: img/logo_niu_dark.png
        date: "2023-07-05"
        toc: true
        code-overflow: scroll
        highlight-style: atom-one
        mermaid: 
          theme: neutral
          fontFamily: arial
          curve: linear
          margin-left: 0
        embed-resources: true
        page-layout: full
my-custom-stuff:
   my-reuseable-variable: "I can use this wherever I want in the markdown, and change it in only once place :)"
---

## v0 (current) {.smaller}
* BrainGlobe Atlas API provides a consistent interface to multiple anatomical atlases
* Separate tools for
    * 3D cell detection (`cellfinder`)
    * 3D atlas registration (`brainreg`)
    * Bulk segmentation (`brainreg-segment`)
    * 3D visualisation (`brainrender`)
* Napari plugins for 3D cell detection (`cellfinder-napari`) and registration (`brainreg-napari`)

## v0 issues {.smaller}
* `brainrender` has considerable technical debt ([brainrender/247](https://github.com/brainglobe/brainrender/issues/247))
* Lots of repositories makes it more difficult to understand which tool does what, and to contribute (e.g. `cellfinder`, `cellfinder-core`, `cellfinder-napari`)
* The mix of napari plugins, Python APIs and command line tools make the ecosystem appear more complicated than it should
* It is not yet possible to carry out all analyses and visualisation within a single platform (napari)
    * Some non-image processing steps need to be carried out seperately (e.g. assigning cells to brain regions)
    * Some visualisation relies on exporting data from napari to brainrender
    
# Planned milestones

## v1 (Q4 2023) {.smaller}
* `brainrender` installable alongside analysis tools (`cellfinder`, `brainreg`, `brainreg-segment`) 
* All tools installable via 

```bash 
pip install brainglobe
```
or
```bash
conda install brainglobe -c conda-forge
```

## v2 (Q2 2024) 1/3 {.smaller}
* Consistent API (TBC) e.g.

```python
from brainglobe import cellfinder
```
or

```python
from brainglobe import cell_detector_3D
```

## v2 (Q2 2024) 2/3 {.smaller}
* Carry out everything in v1 without leaving napari
    * Atlas registration (`brainreg` /  `brainglobe-registration`)
    * Cell detection (`cellfinder`)
    * Assign cells to brain regions (TBC)
    * Analyse arbitrary ROIs (`brainreg-segment`)
        * Soon to be renamed `brainglobe-registration`
    * Visualisation (`brainrender-napari`)

## v2 (Q2 2024) 3/3 {.smaller}
* Automated benchmarks for analysis tools (cell detection & 3D atlas registration) on "real" data
* Combine napari plugins with backend to reduce number of repositories ([BrainGlobe/3](https://github.com/brainglobe/BrainGlobe/issues/3) & ([BrainGlobe/4](https://github.com/brainglobe/BrainGlobe/issues/4))
* Remove existing `cellfinder` CLI to simplify naming ([BrainGlobe/6](https://github.com/brainglobe/BrainGlobe/issues/6))
* Release `brainglobe-workflows`, a collection of scripts to facilitate common tasks (including replacing the `cellfinder` CLI)

## v3 (Q4 2024) {.smaller}
* Intuitive navigation of napari plugins
    * Create "metaplugin"
* Generic layer interpreters ([BrainGlobe/10](https://github.com/brainglobe/BrainGlobe/issues/10))
* Refactored and documented Python API
* Facilitate common analyses/visualisation within napari
    * Plot cells per brain region
* Sample data provided via napari

## v4 (TBC) {.smaller}
* Arbitrary brain subvolume (2D or 3D) registration
* Atlas generation tool (from raw data to BrainGlobe atlas)
* More flexible BrainGlobe atlas API V2 ([bg-atlasapi/141](https://github.com/brainglobe/bg-atlasapi/issues/141))
* New atlases
    * Update Allen adult mouse brain atlas ([bg-atlasgen/46](https://github.com/brainglobe/bg-atlasgen/issues/46))
    * 3D Multimodal Developmental Mouse Brain atlases ([bg-atlasgen/71](https://github.com/brainglobe/bg-atlasgen/issues/71))
    * Human MRI atlases ([bg-atlasgen/85](https://github.com/brainglobe/bg-atlasgen/issues/85))
